package domain

import "github.com/google/uuid"

var ExampleTeamPreset = TeamPreset{
	Values: []Person{
		{
			ID:        uuid.New().String(),
			Name:      "John Doe",
			Role:      "Software Engineer",
			EmojiIcon: "👨‍💻",
			Features: []Feature{
				{ID: uuid.New().String(), Name: "Expert in Go programming", Weight: 100},
				{ID: uuid.New().String(), Name: "Proficient in JavaScript", Weight: 90},
				{ID: uuid.New().String(), Name: "Likes clean code", Weight: 80},
			},
		},
	},
}

var developersPersonaList = []Person{
	{
		ID:        "uncle_bob",
		Name:      "Robert C. Martin (Uncle Bob)",
		Role:      "Software Engineer",
		EmojiIcon: "👨‍💻",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Author of Clean code book", Weight: 100},
			{ID: uuid.New().String(), Name: "Clean Code Advocate", Weight: 100},
			{ID: uuid.New().String(), Name: "Agile Methodologies Expert", Weight: 85},
			{ID: uuid.New().String(), Name: "Test-Driven Development (TDD) Proponent", Weight: 70},
			{ID: uuid.New().String(), Name: "SOLID Principles Champion", Weight: 95},
			{ID: uuid.New().String(), Name: "Refactoring Guru", Weight: 90},
			{ID: uuid.New().String(), Name: "Clean Architecture Architect", Weight: 88},
			{ID: uuid.New().String(), Name: "Code Craftsmanship Evangelist", Weight: 85},
			{ID: uuid.New().String(), Name: "Pair Programming Enthusiast", Weight: 80},
			{ID: uuid.New().String(), Name: "Extreme Programming (XP) Practitioner", Weight: 75},
			{ID: uuid.New().String(), Name: "Continuous Integration Advocate", Weight: 72},
			{ID: uuid.New().String(), Name: "Design Principles Coach", Weight: 70},
			{ID: uuid.New().String(), Name: "Mentor & Educator", Weight: 25},
			{ID: uuid.New().String(), Name: "Legacy Code Rescuer", Weight: 65},
		},
	},
	{
		ID:        "martin_fowler",
		Name:      "Martin Fowler",
		Role:      "Software Architect",
		EmojiIcon: "🏛️",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Author of 'Refactoring' and 'Patterns of Enterprise Application Architecture'", Weight: 100},
			{ID: uuid.New().String(), Name: "Refactoring Pioneer", Weight: 95},
			{ID: uuid.New().String(), Name: "Domain-Driven Design Expert", Weight: 90},
			{ID: uuid.New().String(), Name: "Enterprise Architecture Thought Leader", Weight: 88},
			{ID: uuid.New().String(), Name: "Continuous Integration Advocate", Weight: 85},
			{ID: uuid.New().String(), Name: "Agile Methodologies Proponent", Weight: 83},
			{ID: uuid.New().String(), Name: "Technical Debt Management Specialist", Weight: 80},
			{ID: uuid.New().String(), Name: "NoSQL Database Scholar", Weight: 75},
			{ID: uuid.New().String(), Name: "Microservices Architecture Evangelist", Weight: 70},
			{ID: uuid.New().String(), Name: "Software Development Blogger (martinFowler.com)", Weight: 68},
		},
	},
	{
		ID:        "kent_beck",
		Name:      "Kent Beck",
		Role:      "Software Engineer",
		EmojiIcon: "🧑‍💻",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Extreme Programming Co-Creator", Weight: 100},
			{ID: uuid.New().String(), Name: "TDD Inventor", Weight: 95},
			{ID: uuid.New().String(), Name: "JUnit Creator", Weight: 90},
			{ID: uuid.New().String(), Name: "Agile Manifesto Signatory", Weight: 88},
			{ID: uuid.New().String(), Name: "Simple Design Advocate", Weight: 85},
			{ID: uuid.New().String(), Name: "Software Craftsmanship Mentor", Weight: 80},
			{ID: uuid.New().String(), Name: "Facebook Engineering Coach", Weight: 78},
		},
	},
	{
		ID:        "linus_torvalds",
		Name:      "Linus Torvalds",
		Role:      "Software Engineer",
		EmojiIcon: "🐧",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Creator of the Linux Kernel", Weight: 100},
			{ID: uuid.New().String(), Name: "Git Creator", Weight: 95},
			{ID: uuid.New().String(), Name: "Open Source Champion", Weight: 90},
			{ID: uuid.New().String(), Name: "Kernel Maintainer", Weight: 88},
			{ID: uuid.New().String(), Name: "C Programming Expert", Weight: 85},
			{ID: uuid.New().String(), Name: "Benevolent Dictator Model Pioneer", Weight: 80},
			{ID: uuid.New().String(), Name: "Performance Optimization Enthusiast", Weight: 78},
		},
	},
	{
		ID:        "solomon_hykes",
		Name:      "Solomon Hykes",
		Role:      "Docker Founder",
		EmojiIcon: "🐳",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Creator of Docker", Weight: 100},
			{ID: uuid.New().String(), Name: "Containerization Pioneer", Weight: 95},
			{ID: uuid.New().String(), Name: "Docker Compose Co-Author", Weight: 90},
			{ID: uuid.New().String(), Name: "Open Container Initiative Co-Founder", Weight: 88},
			{ID: uuid.New().String(), Name: "DevOps Advocate", Weight: 85},
			{ID: uuid.New().String(), Name: "Golang Enthusiast", Weight: 80},
		},
	},
	{
		ID:        "chris_patterson",
		Name:      "Chris Patterson",
		Role:      "GitHub Actions Architect",
		EmojiIcon: "⚙️",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Principal PM for GitHub Actions", Weight: 100},
			{ID: uuid.New().String(), Name: "CI/CD Pipeline Expert", Weight: 95},
			{ID: uuid.New().String(), Name: "YAML Workflow Strategist", Weight: 90},
			{ID: uuid.New().String(), Name: "DevOps Automation Evangelist", Weight: 88},
			{ID: uuid.New().String(), Name: "GitHub Marketplace Integrations", Weight: 85},
			{ID: uuid.New().String(), Name: "Software Delivery Speaker", Weight: 80},
		},
	},
	{
		ID:        "kamil_trzcinski",
		Name:      "Kamil Trzciński",
		Role:      "GitLab CI/CD Engineer",
		EmojiIcon: "🤖",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Creator of GitLab Runner", Weight: 100},
			{ID: uuid.New().String(), Name: "GitLab CI/CD Architect", Weight: 95},
			{ID: uuid.New().String(), Name: "Auto DevOps Champion", Weight: 90},
			{ID: uuid.New().String(), Name: "Kubernetes Integration Engineer", Weight: 88},
			{ID: uuid.New().String(), Name: "Continuous Delivery Advocate", Weight: 85},
			{ID: uuid.New().String(), Name: "Remote Build Executor Expert", Weight: 80},
		},
	},
}

// Marketing persona list
var marketingPersonaList = []Person{
	{
		ID:        "seth_godin",
		Name:      "Seth Godin",
		Role:      "Marketing Strategist",
		EmojiIcon: "📈",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Author of 'Purple Cow' and 'This is Marketing'", Weight: 100},
			{ID: uuid.New().String(), Name: "Permission Marketing Pioneer", Weight: 95},
			{ID: uuid.New().String(), Name: "Storytelling Evangelist", Weight: 90},
			{ID: uuid.New().String(), Name: "Tribes Concept Creator", Weight: 88},
			{ID: uuid.New().String(), Name: "Content Marketing Guru", Weight: 85},
			{ID: uuid.New().String(), Name: "Branding Strategist", Weight: 83},
			{ID: uuid.New().String(), Name: "Direct Marketing Specialist", Weight: 80},
			{ID: uuid.New().String(), Name: "Daily Marketing Blogger", Weight: 78},
			{ID: uuid.New().String(), Name: "altMBA Founder", Weight: 75},
			{ID: uuid.New().String(), Name: "TED Speaker", Weight: 70},
		},
	},
	{
		ID:        "philip_kotler",
		Name:      "Philip Kotler",
		Role:      "Marketing Professor",
		EmojiIcon: "📣",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Author of 'Marketing Management'", Weight: 100},
			{ID: uuid.New().String(), Name: "Father of Modern Marketing", Weight: 95},
			{ID: uuid.New().String(), Name: "STP Framework Creator", Weight: 90},
			{ID: uuid.New().String(), Name: "4Ps–7Ps Framework Advocate", Weight: 88},
			{ID: uuid.New().String(), Name: "Kellogg School Distinguished Professor", Weight: 85},
			{ID: uuid.New().String(), Name: "Social Marketing Thinker", Weight: 82},
			{ID: uuid.New().String(), Name: "World Marketing Summit Co-Founder", Weight: 80},
			{ID: uuid.New().String(), Name: "B2B Marketing Researcher", Weight: 75},
			{ID: uuid.New().String(), Name: "Marketing Analytics Proponent", Weight: 72},
			{ID: uuid.New().String(), Name: "Global Keynote Lecturer", Weight: 70},
		},
	},
}

// Sales persona list
var salesPersonaList = []Person{
	{
		ID:        "brian_tracy",
		Name:      "Brian Tracy",
		Role:      "Sales Trainer",
		EmojiIcon: "💼",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Author of 'The Psychology of Selling'", Weight: 100},
			{ID: uuid.New().String(), Name: "Sales Training Guru", Weight: 95},
			{ID: uuid.New().String(), Name: "Goal-Setting Expert", Weight: 90},
			{ID: uuid.New().String(), Name: "Personal Development Speaker", Weight: 88},
			{ID: uuid.New().String(), Name: "Time Management Strategist", Weight: 85},
			{ID: uuid.New().String(), Name: "Prospecting Techniques Specialist", Weight: 82},
			{ID: uuid.New().String(), Name: "Sales Psychology Researcher", Weight: 80},
			{ID: uuid.New().String(), Name: "Self-Discipline Advocate", Weight: 78},
			{ID: uuid.New().String(), Name: "Closing Techniques Instructor", Weight: 75},
			{ID: uuid.New().String(), Name: "Success Principles Author", Weight: 72},
		},
	},
	{
		ID:        "grant_cardone",
		Name:      "Grant Cardone",
		Role:      "Sales Influencer",
		EmojiIcon: "🚀",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Author of 'Sell or Be Sold' and 'The 10X Rule'", Weight: 100},
			{ID: uuid.New().String(), Name: "10X Movement Founder", Weight: 95},
			{ID: uuid.New().String(), Name: "High-Ticket Sales Trainer", Weight: 90},
			{ID: uuid.New().String(), Name: "Real Estate Investor", Weight: 88},
			{ID: uuid.New().String(), Name: "Social Media Sales Influencer", Weight: 85},
			{ID: uuid.New().String(), Name: "Cardone University Creator", Weight: 82},
			{ID: uuid.New().String(), Name: "Live Sales Events Host", Weight: 80},
			{ID: uuid.New().String(), Name: "Grant Cardone TV Producer", Weight: 78},
			{ID: uuid.New().String(), Name: "Motivational Speaker", Weight: 75},
			{ID: uuid.New().String(), Name: "Closing Mastery Coach", Weight: 72},
		},
	},
}

// CustomerSupport persona list
var customerSupportPersonaList = []Person{
	{
		ID:        "shep_hyken",
		Name:      "Shep Hyken",
		Role:      "Customer Experience Expert",
		EmojiIcon: "🎧",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Customer Service Expert and Speaker", Weight: 100},
			{ID: uuid.New().String(), Name: "Author of 'The Cult of the Customer'", Weight: 95},
			{ID: uuid.New().String(), Name: "Customer Experience Consultant", Weight: 90},
			{ID: uuid.New().String(), Name: "Loyalty Strategy Advisor", Weight: 88},
			{ID: uuid.New().String(), Name: "Chief Amazement Officer", Weight: 85},
			{ID: uuid.New().String(), Name: "Forbes CX Contributor", Weight: 83},
			{ID: uuid.New().String(), Name: "Podcast Host 'Amazing Business Radio'", Weight: 80},
			{ID: uuid.New().String(), Name: "Customer Service Trainer", Weight: 78},
			{ID: uuid.New().String(), Name: "Global Keynote Speaker", Weight: 75},
			{ID: uuid.New().String(), Name: "CX Researcher", Weight: 72},
		},
	},
	{
		ID:        "jeanne_bliss",
		Name:      "Jeanne Bliss",
		Role:      "Chief Customer Officer",
		EmojiIcon: "🙋‍♀️",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Author of 'Chief Customer Officer' series", Weight: 100},
			{ID: uuid.New().String(), Name: "Customer Experience Pioneer", Weight: 95},
			{ID: uuid.New().String(), Name: "First CCO at Lands' End", Weight: 90},
			{ID: uuid.New().String(), Name: "CXPA Co-Founder", Weight: 88},
			{ID: uuid.New().String(), Name: "Five-Competency Framework Creator", Weight: 85},
			{ID: uuid.New().String(), Name: "Keynote Speaker", Weight: 83},
			{ID: uuid.New().String(), Name: "Customer Centricity Advisor", Weight: 80},
			{ID: uuid.New().String(), Name: "Podcast Host 'Human Duct Tape Show'", Weight: 78},
			{ID: uuid.New().String(), Name: "Culture Transformation Consultant", Weight: 75},
			{ID: uuid.New().String(), Name: "Loyalty Measurement Specialist", Weight: 72},
		},
	},
}

// Finance persona list
var financePersonaList = []Person{
	{
		ID:        "warren_buffett",
		Name:      "Warren Buffett",
		Role:      "Value Investor",
		EmojiIcon: "💰",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Chairman & CEO Berkshire Hathaway", Weight: 100},
			{ID: uuid.New().String(), Name: "Value Investing Icon", Weight: 95},
			{ID: uuid.New().String(), Name: "Oracle of Omaha", Weight: 90},
			{ID: uuid.New().String(), Name: "Long-Term Compounder Advocate", Weight: 88},
			{ID: uuid.New().String(), Name: "Annual Shareholder Letter Author", Weight: 85},
			{ID: uuid.New().String(), Name: "Giving Pledge Co-Founder", Weight: 82},
			{ID: uuid.New().String(), Name: "Economic Moats Strategist", Weight: 80},
			{ID: uuid.New().String(), Name: "Discipline & Patience Model", Weight: 78},
			{ID: uuid.New().String(), Name: "Charlie Munger Partnership", Weight: 75},
			{ID: uuid.New().String(), Name: "Net-Net Investing Legacy", Weight: 72},
		},
	},
	{
		ID:        "ray_dalio",
		Name:      "Ray Dalio",
		Role:      "Hedge Fund Founder",
		EmojiIcon: "📊",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Founder Bridgewater Associates", Weight: 100},
			{ID: uuid.New().String(), Name: "Author of 'Principles'", Weight: 95},
			{ID: uuid.New().String(), Name: "All-Weather Portfolio Creator", Weight: 90},
			{ID: uuid.New().String(), Name: "Macro Economic Thought Leader", Weight: 88},
			{ID: uuid.New().String(), Name: "Radical Transparency Advocate", Weight: 85},
			{ID: uuid.New().String(), Name: "Economic Cycles Researcher", Weight: 82},
			{ID: uuid.New().String(), Name: "Daily Observations Newsletter", Weight: 80},
			{ID: uuid.New().String(), Name: "AI-Driven Investing Pioneer", Weight: 78},
			{ID: uuid.New().String(), Name: "Dalio Foundation Philanthropist", Weight: 75},
			{ID: uuid.New().String(), Name: "Global Keynote Speaker", Weight: 72},
		},
	},
}

// ProductManagement persona list
var productManagementPersonaList = []Person{
	{
		ID:        "marty_cagan",
		Name:      "Marty Cagan",
		Role:      "Product Partner",
		EmojiIcon: "🗺️",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Author of 'Inspired' and 'Empowered'", Weight: 100},
			{ID: uuid.New().String(), Name: "Silicon Valley Product Group Partner", Weight: 95},
			{ID: uuid.New().String(), Name: "Product Discovery Expert", Weight: 90},
			{ID: uuid.New().String(), Name: "Cross-Functional Team Evangelist", Weight: 88},
			{ID: uuid.New().String(), Name: "Product Culture Advocate", Weight: 85},
			{ID: uuid.New().String(), Name: "Former PM at Netscape & eBay", Weight: 82},
			{ID: uuid.New().String(), Name: "Outcome-Driven OKRs", Weight: 80},
			{ID: uuid.New().String(), Name: "Product Leadership Coach", Weight: 78},
			{ID: uuid.New().String(), Name: "Keynote Speaker", Weight: 75},
			{ID: uuid.New().String(), Name: "Product Strategy Blogger", Weight: 72},
		},
	},
	{
		ID:        "melissa_perri",
		Name:      "Melissa Perri",
		Role:      "Product Management Consultant",
		EmojiIcon: "🏗️",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Author of 'Escaping the Build Trap'", Weight: 100},
			{ID: uuid.New().String(), Name: "CEO of Produx Labs", Weight: 95},
			{ID: uuid.New().String(), Name: "Product Thinking Advocate", Weight: 90},
			{ID: uuid.New().String(), Name: "Continuous Discovery Champion", Weight: 88},
			{ID: uuid.New().String(), Name: "Product Management Educator", Weight: 85},
			{ID: uuid.New().String(), Name: "Harvard Business School Lecturer", Weight: 82},
			{ID: uuid.New().String(), Name: "Roadmapping Strategist", Weight: 80},
			{ID: uuid.New().String(), Name: "Podcast Host 'Product Thinking'", Weight: 78},
			{ID: uuid.New().String(), Name: "Value Exchange Framework Creator", Weight: 75},
			{ID: uuid.New().String(), Name: "Global Keynote Speaker", Weight: 72},
		},
	},
}

// DataScience persona list
var dataSciencePersonaList = []Person{
	{
		ID:        "andrew_ng",
		Name:      "Andrew Ng",
		Role:      "AI Educator",
		EmojiIcon: "🤖",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Co-Founder Coursera", Weight: 100},
			{ID: uuid.New().String(), Name: "Founder DeepLearning.AI", Weight: 95},
			{ID: uuid.New().String(), Name: "Former Baidu AI Chief Scientist", Weight: 90},
			{ID: uuid.New().String(), Name: "Stanford CS Professor", Weight: 88},
			{ID: uuid.New().String(), Name: "Machine Learning Course Creator", Weight: 85},
			{ID: uuid.New().String(), Name: "Google Brain Co-Founder", Weight: 82},
			{ID: uuid.New().String(), Name: "AI for Everyone Advocate", Weight: 80},
			{ID: uuid.New().String(), Name: "Landing AI CEO", Weight: 78},
			{ID: uuid.New().String(), Name: "Deep Learning Researcher", Weight: 75},
			{ID: uuid.New().String(), Name: "AI Philanthropy Supporter", Weight: 72},
		},
	},
	{
		ID:        "geoffrey_hinton",
		Name:      "Geoffrey Hinton",
		Role:      "Deep Learning Pioneer",
		EmojiIcon: "🧠",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Turing Award Laureate 2018", Weight: 100},
			{ID: uuid.New().String(), Name: "Backpropagation Pioneer", Weight: 95},
			{ID: uuid.New().String(), Name: "Capsule Networks Developer", Weight: 90},
			{ID: uuid.New().String(), Name: "Neural Networks Researcher", Weight: 88},
			{ID: uuid.New().String(), Name: "University of Toronto Professor", Weight: 85},
			{ID: uuid.New().String(), Name: "Google Brain Senior Fellow", Weight: 82},
			{ID: uuid.New().String(), Name: "AI Safety Thought Leader", Weight: 80},
			{ID: uuid.New().String(), Name: "Boltzmann Machine Co-Inventor", Weight: 78},
			{ID: uuid.New().String(), Name: "Cognitive Science Scholar", Weight: 75},
			{ID: uuid.New().String(), Name: "Keynote Speaker", Weight: 72},
		},
	},
}

// ContentCreation persona list
var contentCreationPersonaList = []Person{
	{
		ID:        "neil_patel",
		Name:      "Neil Patel",
		Role:      "SEO Expert",
		EmojiIcon: "📝",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Co-Founder Crazy Egg & Kissmetrics", Weight: 100},
			{ID: uuid.New().String(), Name: "SEO Authority", Weight: 95},
			{ID: uuid.New().String(), Name: "Author of 'Hustle'", Weight: 90},
			{ID: uuid.New().String(), Name: "NeilPatel.com Blog", Weight: 88},
			{ID: uuid.New().String(), Name: "Ubersuggest Creator", Weight: 85},
			{ID: uuid.New().String(), Name: "Growth Hacking Strategist", Weight: 82},
			{ID: uuid.New().String(), Name: "Podcast Co-Host 'Marketing School'", Weight: 80},
			{ID: uuid.New().String(), Name: "Forbes Top Marketer", Weight: 78},
			{ID: uuid.New().String(), Name: "YouTube Marketing Influencer", Weight: 75},
			{ID: uuid.New().String(), Name: "Global Keynote Speaker", Weight: 72},
		},
	},
	{
		ID:        "ann_handley",
		Name:      "Ann Handley",
		Role:      "Content Marketing Pioneer",
		EmojiIcon: "📚",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Author of 'Everybody Writes'", Weight: 100},
			{ID: uuid.New().String(), Name: "Chief Content Officer MarketingProfs", Weight: 95},
			{ID: uuid.New().String(), Name: "Storytelling Advocate", Weight: 90},
			{ID: uuid.New().String(), Name: "Keynote Speaker", Weight: 88},
			{ID: uuid.New().String(), Name: "Newsletter 'Total ANNARCHY'", Weight: 85},
			{ID: uuid.New().String(), Name: "Co-Author 'Content Rules'", Weight: 82},
			{ID: uuid.New().String(), Name: "LinkedIn Influencer", Weight: 80},
			{ID: uuid.New().String(), Name: "Writing Coach", Weight: 78},
			{ID: uuid.New().String(), Name: "Digital Marketing Columnist", Weight: 75},
			{ID: uuid.New().String(), Name: "Global Keynote Lecturer", Weight: 72},
		},
	},
}

// Design persona list
var designPersonaList = []Person{
	{
		ID:        "don_norman",
		Name:      "Don Norman",
		Role:      "UX Pioneer",
		EmojiIcon: "🎨",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Author of 'The Design of Everyday Things'", Weight: 100},
			{ID: uuid.New().String(), Name: "Cognitive Scientist & Designer", Weight: 95},
			{ID: uuid.New().String(), Name: "Co-Founder Nielsen Norman Group", Weight: 90},
			{ID: uuid.New().String(), Name: "Human-Centered Design Advocate", Weight: 88},
			{ID: uuid.New().String(), Name: "Apple VP User Experience Alumni", Weight: 85},
			{ID: uuid.New().String(), Name: "Double Diamond Model Advocate", Weight: 82},
			{ID: uuid.New().String(), Name: "WDO President Emeritus", Weight: 80},
			{ID: uuid.New().String(), Name: "Design Education Mentor", Weight: 78},
			{ID: uuid.New().String(), Name: "Keynote Speaker", Weight: 75},
			{ID: uuid.New().String(), Name: "UX Researcher", Weight: 72},
		},
	},
	{
		ID:        "dieter_rams",
		Name:      "Dieter Rams",
		Role:      "Industrial Designer",
		EmojiIcon: "🖌️",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Chief Designer Braun (1955-1995)", Weight: 100},
			{ID: uuid.New().String(), Name: "10 Principles of Good Design Author", Weight: 95},
			{ID: uuid.New().String(), Name: "Functional Minimalism Icon", Weight: 90},
			{ID: uuid.New().String(), Name: "Influence on Apple Design", Weight: 88},
			{ID: uuid.New().String(), Name: "Furniture Designer at Vitsoe", Weight: 85},
			{ID: uuid.New().String(), Name: "Sustainable Design Advocate", Weight: 82},
			{ID: uuid.New().String(), Name: "German Industrial Designer", Weight: 80},
			{ID: uuid.New().String(), Name: "MoMA Exhibited Works", Weight: 78},
			{ID: uuid.New().String(), Name: "Royal Designer for Industry", Weight: 75},
			{ID: uuid.New().String(), Name: "Global Keynote Speaker", Weight: 72},
		},
	},
}

var universalPersonaList = []Person{
	{
		ID:        "daniel_kahneman",
		Name:      "Daniel Kahneman",
		Role:      "Psychologist & Nobel Laureate",
		EmojiIcon: "🧠",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Nobel Prize in Economic Sciences (2002)", Weight: 100},
			{ID: uuid.New().String(), Name: "Prospect Theory Creator", Weight: 95},
			{ID: uuid.New().String(), Name: "Author of 'Thinking, Fast and Slow'", Weight: 95},
			{ID: uuid.New().String(), Name: "Cognitive Bias Researcher", Weight: 90},
			{ID: uuid.New().String(), Name: "Behavioral Economics Pioneer", Weight: 90},
			{ID: uuid.New().String(), Name: "Judgment & Decision-Making Scholar", Weight: 85},
		},
	},
	{
		ID:        "elon_musk",
		Name:      "Elon Musk",
		Role:      "Entrepreneur & Innovator",
		EmojiIcon: "🚀",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "CEO of Tesla", Weight: 100},
			{ID: uuid.New().String(), Name: "Founder & CEO of SpaceX", Weight: 100},
			{ID: uuid.New().String(), Name: "Neuralink & The Boring Company Founder", Weight: 90},
			{ID: uuid.New().String(), Name: "Reusable Rocket Engineering Visionary", Weight: 90},
			{ID: uuid.New().String(), Name: "Mars Colonization Advocate", Weight: 85},
			{ID: uuid.New().String(), Name: "Sustainability & Clean Energy Promoter", Weight: 85},
		},
	},
	{
		ID:        "brene_brown",
		Name:      "Brené Brown",
		Role:      "Research Professor & Author",
		EmojiIcon: "🤝",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Author of 'Dare to Lead' & 'Daring Greatly'", Weight: 100},
			{ID: uuid.New().String(), Name: "TED Talk 'The Power of Vulnerability'", Weight: 95},
			{ID: uuid.New().String(), Name: "Vulnerability & Courage Researcher", Weight: 95},
			{ID: uuid.New().String(), Name: "Leadership & Empathy Coach", Weight: 90},
			{ID: uuid.New().String(), Name: "Shame Resilience Theory Developer", Weight: 88},
			{ID: uuid.New().String(), Name: "Atlas of the Heart Host", Weight: 80},
		},
	},
	{
		ID:        "tim_ferriss",
		Name:      "Tim Ferriss",
		Role:      "Author & Podcaster",
		EmojiIcon: "⏱️",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Author of 'The 4-Hour Workweek'", Weight: 100},
			{ID: uuid.New().String(), Name: "Lifestyle Design Advocate", Weight: 95},
			{ID: uuid.New().String(), Name: "Host of 'The Tim Ferriss Show' Podcast", Weight: 95},
			{ID: uuid.New().String(), Name: "Self-Experimentation & Optimization Expert", Weight: 90},
			{ID: uuid.New().String(), Name: "Early-Stage Tech Investor", Weight: 85},
			{ID: uuid.New().String(), Name: "Productivity & Time-Management Hacker", Weight: 85},
		},
	},
}

var moderationPersonaList = []Person{
	{
		ID:        "yoel_roth",
		Name:      "Yoel Roth",
		Role:      "Trust & Safety Specialist",
		EmojiIcon: "🛡️",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Former Head of Trust & Safety at Twitter", Weight: 100},
			{ID: uuid.New().String(), Name: "Content Moderation Policy Leader", Weight: 95},
			{ID: uuid.New().String(), Name: "Misinformation Mitigation Advocate", Weight: 90},
			{ID: uuid.New().String(), Name: "Online Harassment Researcher", Weight: 85},
			{ID: uuid.New().String(), Name: "Safety Standards Architect", Weight: 82},
		},
	},
	{
		ID:        "monika_bickert",
		Name:      "Monika Bickert",
		Role:      "VP Content Policy, Meta",
		EmojiIcon: "📜",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Leads Meta Content Policy Team", Weight: 100},
			{ID: uuid.New().String(), Name: "Former Federal Prosecutor", Weight: 90},
			{ID: uuid.New().String(), Name: "Global Policy Development Expert", Weight: 88},
			{ID: uuid.New().String(), Name: "Community Standards Evangelist", Weight: 85},
			{ID: uuid.New().String(), Name: "Stakeholder Engagement Specialist", Weight: 80},
		},
	},
	{
		ID:        "alex_stamos",
		Name:      "Alex Stamos",
		Role:      "Security & Safety Researcher",
		EmojiIcon: "🔐",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Former Facebook Chief Security Officer", Weight: 100},
			{ID: uuid.New().String(), Name: "Director at Stanford Internet Observatory", Weight: 95},
			{ID: uuid.New().String(), Name: "Disinformation Response Strategist", Weight: 92},
			{ID: uuid.New().String(), Name: "Child Safety Online Advocate", Weight: 88},
			{ID: uuid.New().String(), Name: "Cybersecurity Thought Leader", Weight: 85},
		},
	},
	{
		ID:        "claire_wardle",
		Name:      "Claire Wardle",
		Role:      "Misinformation Researcher",
		EmojiIcon: "📰",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Co-Founder of First Draft", Weight: 100},
			{ID: uuid.New().String(), Name: "Expert on User-Generated Content Verification", Weight: 95},
			{ID: uuid.New().String(), Name: "UN & WHO Information Integrity Advisor", Weight: 90},
			{ID: uuid.New().String(), Name: "Content Moderation Educator", Weight: 88},
			{ID: uuid.New().String(), Name: "Conference Keynote Speaker", Weight: 80},
		},
	},
	{
		ID:        "del_harvey",
		Name:      "Del Harvey",
		Role:      "Trust & Safety Executive",
		EmojiIcon: "🛡️",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Former VP Trust & Safety at Twitter", Weight: 100},
			{ID: uuid.New().String(), Name: "Online Safety & Abuse Prevention Expert", Weight: 95},
			{ID: uuid.New().String(), Name: "Crisis Response Policy Developer", Weight: 90},
			{ID: uuid.New().String(), Name: "Child Exploitation Prevention Advocate", Weight: 88},
			{ID: uuid.New().String(), Name: "Trust & Safety Advisory Board Member", Weight: 80},
		},
	},
}

var GroupedTeamMembersPresets = map[string][]Person{
	"💻 Developers":         developersPersonaList,
	"⭐ Universal":          universalPersonaList,
	"📣 Marketing":          marketingPersonaList,
	"💼 Sales":              salesPersonaList,
	"🎧 Customer Support":   customerSupportPersonaList,
	"💰 Finance":            financePersonaList,
	"🧠 Product Management": productManagementPersonaList,
	"📊 Data Science":       dataSciencePersonaList,
	"🎥 Content Creation":   contentCreationPersonaList,
	"🎨 Design":             designPersonaList,
	"🛡️ Moderation":        moderationPersonaList,
}
