package domain

import "github.com/google/uuid"

var ExampleTeamPreset = TeamPreset{
	Values: []Person{
		{
			ID:        uuid.New().String(),
			Name:      "John Doe",
			Role:      "Software Engineer",
			EmojiIcon: "👨‍💻",
			Features: []Feature{
				{ID: uuid.New().String(), Name: "Expert in Go programming", Weight: 100},
				{ID: uuid.New().String(), Name: "Proficient in JavaScript", Weight: 90},
				{ID: uuid.New().String(), Name: "Likes clean code", Weight: 80},
			},
		},
	},
}

var developersPersonaList = []Person{
	{
		ID:        "uncle_bob",
		Name:      "Robert C. Martin (Uncle Bob)",
		Role:      "Software Engineer",
		EmojiIcon: "👨‍💻",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Author of Clean code book", Weight: 100},
			{ID: uuid.New().String(), Name: "Clean Code Advocate", Weight: 100},
			{ID: uuid.New().String(), Name: "Agile Methodologies Expert", Weight: 85},
			{ID: uuid.New().String(), Name: "Test-Driven Development (TDD) Proponent", Weight: 70},
			{ID: uuid.New().String(), Name: "SOLID Principles Champion", Weight: 95},
			{ID: uuid.New().String(), Name: "Refactoring Guru", Weight: 90},
			{ID: uuid.New().String(), Name: "Clean Architecture Architect", Weight: 88},
			{ID: uuid.New().String(), Name: "Code Craftsmanship Evangelist", Weight: 85},
			{ID: uuid.New().String(), Name: "Pair Programming Enthusiast", Weight: 80},
			{ID: uuid.New().String(), Name: "Extreme Programming (XP) Practitioner", Weight: 75},
			{ID: uuid.New().String(), Name: "Continuous Integration Advocate", Weight: 72},
			{ID: uuid.New().String(), Name: "Design Principles Coach", Weight: 70},
			{ID: uuid.New().String(), Name: "Mentor & Educator", Weight: 25},
			{ID: uuid.New().String(), Name: "Legacy Code Rescuer", Weight: 65},
		},
	},
	{
		ID:        "martin_fowler",
		Name:      "Martin Fowler",
		Role:      "Software Architect",
		EmojiIcon: "🏛️",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Author of 'Refactoring' and 'Patterns of Enterprise Application Architecture'", Weight: 100},
			{ID: uuid.New().String(), Name: "Refactoring Pioneer", Weight: 95},
			{ID: uuid.New().String(), Name: "Domain-Driven Design Expert", Weight: 90},
			{ID: uuid.New().String(), Name: "Enterprise Architecture Thought Leader", Weight: 88},
			{ID: uuid.New().String(), Name: "Continuous Integration Advocate", Weight: 85},
			{ID: uuid.New().String(), Name: "Agile Methodologies Proponent", Weight: 83},
			{ID: uuid.New().String(), Name: "Technical Debt Management Specialist", Weight: 80},
			{ID: uuid.New().String(), Name: "NoSQL Database Scholar", Weight: 75},
			{ID: uuid.New().String(), Name: "Microservices Architecture Evangelist", Weight: 70},
			{ID: uuid.New().String(), Name: "Software Development Blogger (martinFowler.com)", Weight: 68},
		},
	},
	{
		ID:        "kent_beck",
		Name:      "Kent Beck",
		Role:      "Software Engineer",
		EmojiIcon: "🧑‍💻",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Extreme Programming Co-Creator", Weight: 100},
			{ID: uuid.New().String(), Name: "TDD Inventor", Weight: 95},
			{ID: uuid.New().String(), Name: "JUnit Creator", Weight: 90},
			{ID: uuid.New().String(), Name: "Agile Manifesto Signatory", Weight: 88},
			{ID: uuid.New().String(), Name: "Simple Design Advocate", Weight: 85},
			{ID: uuid.New().String(), Name: "Software Craftsmanship Mentor", Weight: 80},
			{ID: uuid.New().String(), Name: "Facebook Engineering Coach", Weight: 78},
		},
	},
	{
		ID:        "linus_torvalds",
		Name:      "Linus Torvalds",
		Role:      "Software Engineer",
		EmojiIcon: "🐧",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Creator of the Linux Kernel", Weight: 100},
			{ID: uuid.New().String(), Name: "Git Creator", Weight: 95},
			{ID: uuid.New().String(), Name: "Open Source Champion", Weight: 90},
			{ID: uuid.New().String(), Name: "Kernel Maintainer", Weight: 88},
			{ID: uuid.New().String(), Name: "C Programming Expert", Weight: 85},
			{ID: uuid.New().String(), Name: "Benevolent Dictator Model Pioneer", Weight: 80},
			{ID: uuid.New().String(), Name: "Performance Optimization Enthusiast", Weight: 78},
		},
	},
	{
		ID:        "solomon_hykes",
		Name:      "Solomon Hykes",
		Role:      "Docker Founder",
		EmojiIcon: "🐳",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Creator of Docker", Weight: 100},
			{ID: uuid.New().String(), Name: "Containerization Pioneer", Weight: 95},
			{ID: uuid.New().String(), Name: "Docker Compose Co-Author", Weight: 90},
			{ID: uuid.New().String(), Name: "Open Container Initiative Co-Founder", Weight: 88},
			{ID: uuid.New().String(), Name: "DevOps Advocate", Weight: 85},
			{ID: uuid.New().String(), Name: "Golang Enthusiast", Weight: 80},
		},
	},
	{
		ID:        "chris_patterson",
		Name:      "Chris Patterson",
		Role:      "GitHub Actions Architect",
		EmojiIcon: "⚙️",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Principal PM for GitHub Actions", Weight: 100},
			{ID: uuid.New().String(), Name: "CI/CD Pipeline Expert", Weight: 95},
			{ID: uuid.New().String(), Name: "YAML Workflow Strategist", Weight: 90},
			{ID: uuid.New().String(), Name: "DevOps Automation Evangelist", Weight: 88},
			{ID: uuid.New().String(), Name: "GitHub Marketplace Integrations", Weight: 85},
			{ID: uuid.New().String(), Name: "Software Delivery Speaker", Weight: 80},
		},
	},
	{
		ID:        "kamil_trzcinski",
		Name:      "Kamil Trzciński",
		Role:      "GitLab CI/CD Engineer",
		EmojiIcon: "🤖",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Creator of GitLab Runner", Weight: 100},
			{ID: uuid.New().String(), Name: "GitLab CI/CD Architect", Weight: 95},
			{ID: uuid.New().String(), Name: "Auto DevOps Champion", Weight: 90},
			{ID: uuid.New().String(), Name: "Kubernetes Integration Engineer", Weight: 88},
			{ID: uuid.New().String(), Name: "Continuous Delivery Advocate", Weight: 85},
			{ID: uuid.New().String(), Name: "Remote Build Executor Expert", Weight: 80},
		},
	},
}

// Marketing persona list
var marketingPersonaList = []Person{
	{
		ID:        "seth_godin",
		Name:      "Seth Godin",
		Role:      "Marketing Strategist",
		EmojiIcon: "📈",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Author of 'Purple Cow' and 'This is Marketing'", Weight: 100},
			{ID: uuid.New().String(), Name: "Permission Marketing Pioneer", Weight: 95},
			{ID: uuid.New().String(), Name: "Storytelling Evangelist", Weight: 90},
			{ID: uuid.New().String(), Name: "Tribes Concept Creator", Weight: 88},
			{ID: uuid.New().String(), Name: "Content Marketing Guru", Weight: 85},
			{ID: uuid.New().String(), Name: "Branding Strategist", Weight: 83},
			{ID: uuid.New().String(), Name: "Direct Marketing Specialist", Weight: 80},
			{ID: uuid.New().String(), Name: "Daily Marketing Blogger", Weight: 78},
			{ID: uuid.New().String(), Name: "altMBA Founder", Weight: 75},
			{ID: uuid.New().String(), Name: "TED Speaker", Weight: 70},
		},
	},
	{
		ID:        "philip_kotler",
		Name:      "Philip Kotler",
		Role:      "Marketing Professor",
		EmojiIcon: "📣",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Author of 'Marketing Management'", Weight: 100},
			{ID: uuid.New().String(), Name: "Father of Modern Marketing", Weight: 95},
			{ID: uuid.New().String(), Name: "STP Framework Creator", Weight: 90},
			{ID: uuid.New().String(), Name: "4Ps–7Ps Framework Advocate", Weight: 88},
			{ID: uuid.New().String(), Name: "Kellogg School Distinguished Professor", Weight: 85},
			{ID: uuid.New().String(), Name: "Social Marketing Thinker", Weight: 82},
			{ID: uuid.New().String(), Name: "World Marketing Summit Co-Founder", Weight: 80},
			{ID: uuid.New().String(), Name: "B2B Marketing Researcher", Weight: 75},
			{ID: uuid.New().String(), Name: "Marketing Analytics Proponent", Weight: 72},
			{ID: uuid.New().String(), Name: "Global Keynote Lecturer", Weight: 70},
		},
	},
}

// Sales persona list
var salesPersonaList = []Person{
	{
		ID:        "brian_tracy",
		Name:      "Brian Tracy",
		Role:      "Sales Trainer",
		EmojiIcon: "💼",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Author of 'The Psychology of Selling'", Weight: 100},
			{ID: uuid.New().String(), Name: "Sales Training Guru", Weight: 95},
			{ID: uuid.New().String(), Name: "Goal-Setting Expert", Weight: 90},
			{ID: uuid.New().String(), Name: "Personal Development Speaker", Weight: 88},
			{ID: uuid.New().String(), Name: "Time Management Strategist", Weight: 85},
			{ID: uuid.New().String(), Name: "Prospecting Techniques Specialist", Weight: 82},
			{ID: uuid.New().String(), Name: "Sales Psychology Researcher", Weight: 80},
			{ID: uuid.New().String(), Name: "Self-Discipline Advocate", Weight: 78},
			{ID: uuid.New().String(), Name: "Closing Techniques Instructor", Weight: 75},
			{ID: uuid.New().String(), Name: "Success Principles Author", Weight: 72},
		},
	},
	{
		ID:        "grant_cardone",
		Name:      "Grant Cardone",
		Role:      "Sales Influencer",
		EmojiIcon: "🚀",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Author of 'Sell or Be Sold' and 'The 10X Rule'", Weight: 100},
			{ID: uuid.New().String(), Name: "10X Movement Founder", Weight: 95},
			{ID: uuid.New().String(), Name: "High-Ticket Sales Trainer", Weight: 90},
			{ID: uuid.New().String(), Name: "Real Estate Investor", Weight: 88},
			{ID: uuid.New().String(), Name: "Social Media Sales Influencer", Weight: 85},
			{ID: uuid.New().String(), Name: "Cardone University Creator", Weight: 82},
			{ID: uuid.New().String(), Name: "Live Sales Events Host", Weight: 80},
			{ID: uuid.New().String(), Name: "Grant Cardone TV Producer", Weight: 78},
			{ID: uuid.New().String(), Name: "Motivational Speaker", Weight: 75},
			{ID: uuid.New().String(), Name: "Closing Mastery Coach", Weight: 72},
		},
	},
}

// CustomerSupport persona list
var customerSupportPersonaList = []Person{
	{
		ID:        "shep_hyken",
		Name:      "Shep Hyken",
		Role:      "Customer Experience Expert",
		EmojiIcon: "🎧",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Customer Service Expert and Speaker", Weight: 100},
			{ID: uuid.New().String(), Name: "Author of 'The Cult of the Customer'", Weight: 95},
			{ID: uuid.New().String(), Name: "Customer Experience Consultant", Weight: 90},
			{ID: uuid.New().String(), Name: "Loyalty Strategy Advisor", Weight: 88},
			{ID: uuid.New().String(), Name: "Chief Amazement Officer", Weight: 85},
			{ID: uuid.New().String(), Name: "Forbes CX Contributor", Weight: 83},
			{ID: uuid.New().String(), Name: "Podcast Host 'Amazing Business Radio'", Weight: 80},
			{ID: uuid.New().String(), Name: "Customer Service Trainer", Weight: 78},
			{ID: uuid.New().String(), Name: "Global Keynote Speaker", Weight: 75},
			{ID: uuid.New().String(), Name: "CX Researcher", Weight: 72},
		},
	},
	{
		ID:        "jeanne_bliss",
		Name:      "Jeanne Bliss",
		Role:      "Chief Customer Officer",
		EmojiIcon: "🙋‍♀️",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Author of 'Chief Customer Officer' series", Weight: 100},
			{ID: uuid.New().String(), Name: "Customer Experience Pioneer", Weight: 95},
			{ID: uuid.New().String(), Name: "First CCO at Lands' End", Weight: 90},
			{ID: uuid.New().String(), Name: "CXPA Co-Founder", Weight: 88},
			{ID: uuid.New().String(), Name: "Five-Competency Framework Creator", Weight: 85},
			{ID: uuid.New().String(), Name: "Keynote Speaker", Weight: 83},
			{ID: uuid.New().String(), Name: "Customer Centricity Advisor", Weight: 80},
			{ID: uuid.New().String(), Name: "Podcast Host 'Human Duct Tape Show'", Weight: 78},
			{ID: uuid.New().String(), Name: "Culture Transformation Consultant", Weight: 75},
			{ID: uuid.New().String(), Name: "Loyalty Measurement Specialist", Weight: 72},
		},
	},
}

// Finance persona list
var financePersonaList = []Person{
	{
		ID:        "warren_buffett",
		Name:      "Warren Buffett",
		Role:      "Value Investor",
		EmojiIcon: "💰",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Chairman & CEO Berkshire Hathaway", Weight: 100},
			{ID: uuid.New().String(), Name: "Value Investing Icon", Weight: 95},
			{ID: uuid.New().String(), Name: "Oracle of Omaha", Weight: 90},
			{ID: uuid.New().String(), Name: "Long-Term Compounder Advocate", Weight: 88},
			{ID: uuid.New().String(), Name: "Annual Shareholder Letter Author", Weight: 85},
			{ID: uuid.New().String(), Name: "Giving Pledge Co-Founder", Weight: 82},
			{ID: uuid.New().String(), Name: "Economic Moats Strategist", Weight: 80},
			{ID: uuid.New().String(), Name: "Discipline & Patience Model", Weight: 78},
			{ID: uuid.New().String(), Name: "Charlie Munger Partnership", Weight: 75},
			{ID: uuid.New().String(), Name: "Net-Net Investing Legacy", Weight: 72},
		},
	},
	{
		ID:        "ray_dalio",
		Name:      "Ray Dalio",
		Role:      "Hedge Fund Founder",
		EmojiIcon: "📊",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Founder Bridgewater Associates", Weight: 100},
			{ID: uuid.New().String(), Name: "Author of 'Principles'", Weight: 95},
			{ID: uuid.New().String(), Name: "All-Weather Portfolio Creator", Weight: 90},
			{ID: uuid.New().String(), Name: "Macro Economic Thought Leader", Weight: 88},
			{ID: uuid.New().String(), Name: "Radical Transparency Advocate", Weight: 85},
			{ID: uuid.New().String(), Name: "Economic Cycles Researcher", Weight: 82},
			{ID: uuid.New().String(), Name: "Daily Observations Newsletter", Weight: 80},
			{ID: uuid.New().String(), Name: "AI-Driven Investing Pioneer", Weight: 78},
			{ID: uuid.New().String(), Name: "Dalio Foundation Philanthropist", Weight: 75},
			{ID: uuid.New().String(), Name: "Global Keynote Speaker", Weight: 72},
		},
	},
}

// ProductManagement persona list
var productManagementPersonaList = []Person{
	{
		ID:        "marty_cagan",
		Name:      "Marty Cagan",
		Role:      "Product Partner",
		EmojiIcon: "🗺️",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Author of 'Inspired' and 'Empowered'", Weight: 100},
			{ID: uuid.New().String(), Name: "Silicon Valley Product Group Partner", Weight: 95},
			{ID: uuid.New().String(), Name: "Product Discovery Expert", Weight: 90},
			{ID: uuid.New().String(), Name: "Cross-Functional Team Evangelist", Weight: 88},
			{ID: uuid.New().String(), Name: "Product Culture Advocate", Weight: 85},
			{ID: uuid.New().String(), Name: "Former PM at Netscape & eBay", Weight: 82},
			{ID: uuid.New().String(), Name: "Outcome-Driven OKRs", Weight: 80},
			{ID: uuid.New().String(), Name: "Product Leadership Coach", Weight: 78},
			{ID: uuid.New().String(), Name: "Keynote Speaker", Weight: 75},
			{ID: uuid.New().String(), Name: "Product Strategy Blogger", Weight: 72},
		},
	},
	{
		ID:        "melissa_perri",
		Name:      "Melissa Perri",
		Role:      "Product Management Consultant",
		EmojiIcon: "🏗️",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Author of 'Escaping the Build Trap'", Weight: 100},
			{ID: uuid.New().String(), Name: "CEO of Produx Labs", Weight: 95},
			{ID: uuid.New().String(), Name: "Product Thinking Advocate", Weight: 90},
			{ID: uuid.New().String(), Name: "Continuous Discovery Champion", Weight: 88},
			{ID: uuid.New().String(), Name: "Product Management Educator", Weight: 85},
			{ID: uuid.New().String(), Name: "Harvard Business School Lecturer", Weight: 82},
			{ID: uuid.New().String(), Name: "Roadmapping Strategist", Weight: 80},
			{ID: uuid.New().String(), Name: "Podcast Host 'Product Thinking'", Weight: 78},
			{ID: uuid.New().String(), Name: "Value Exchange Framework Creator", Weight: 75},
			{ID: uuid.New().String(), Name: "Global Keynote Speaker", Weight: 72},
		},
	},
}

// DataScience persona list
var dataSciencePersonaList = []Person{
	{
		ID:        "andrew_ng",
		Name:      "Andrew Ng",
		Role:      "AI Educator",
		EmojiIcon: "🤖",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Co-Founder Coursera", Weight: 100},
			{ID: uuid.New().String(), Name: "Founder DeepLearning.AI", Weight: 95},
			{ID: uuid.New().String(), Name: "Former Baidu AI Chief Scientist", Weight: 90},
			{ID: uuid.New().String(), Name: "Stanford CS Professor", Weight: 88},
			{ID: uuid.New().String(), Name: "Machine Learning Course Creator", Weight: 85},
			{ID: uuid.New().String(), Name: "Google Brain Co-Founder", Weight: 82},
			{ID: uuid.New().String(), Name: "AI for Everyone Advocate", Weight: 80},
			{ID: uuid.New().String(), Name: "Landing AI CEO", Weight: 78},
			{ID: uuid.New().String(), Name: "Deep Learning Researcher", Weight: 75},
			{ID: uuid.New().String(), Name: "AI Philanthropy Supporter", Weight: 72},
		},
	},
	{
		ID:        "geoffrey_hinton",
		Name:      "Geoffrey Hinton",
		Role:      "Deep Learning Pioneer",
		EmojiIcon: "🧠",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Turing Award Laureate 2018", Weight: 100},
			{ID: uuid.New().String(), Name: "Backpropagation Pioneer", Weight: 95},
			{ID: uuid.New().String(), Name: "Capsule Networks Developer", Weight: 90},
			{ID: uuid.New().String(), Name: "Neural Networks Researcher", Weight: 88},
			{ID: uuid.New().String(), Name: "University of Toronto Professor", Weight: 85},
			{ID: uuid.New().String(), Name: "Google Brain Senior Fellow", Weight: 82},
			{ID: uuid.New().String(), Name: "AI Safety Thought Leader", Weight: 80},
			{ID: uuid.New().String(), Name: "Boltzmann Machine Co-Inventor", Weight: 78},
			{ID: uuid.New().String(), Name: "Cognitive Science Scholar", Weight: 75},
			{ID: uuid.New().String(), Name: "Keynote Speaker", Weight: 72},
		},
	},
}

// ContentCreation persona list
var contentCreationPersonaList = []Person{
	{
		ID:        "neil_patel",
		Name:      "Neil Patel",
		Role:      "SEO Expert",
		EmojiIcon: "📝",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Co-Founder Crazy Egg & Kissmetrics", Weight: 100},
			{ID: uuid.New().String(), Name: "SEO Authority", Weight: 95},
			{ID: uuid.New().String(), Name: "Author of 'Hustle'", Weight: 90},
			{ID: uuid.New().String(), Name: "NeilPatel.com Blog", Weight: 88},
			{ID: uuid.New().String(), Name: "Ubersuggest Creator", Weight: 85},
			{ID: uuid.New().String(), Name: "Growth Hacking Strategist", Weight: 82},
			{ID: uuid.New().String(), Name: "Podcast Co-Host 'Marketing School'", Weight: 80},
			{ID: uuid.New().String(), Name: "Forbes Top Marketer", Weight: 78},
			{ID: uuid.New().String(), Name: "YouTube Marketing Influencer", Weight: 75},
			{ID: uuid.New().String(), Name: "Global Keynote Speaker", Weight: 72},
		},
	},
	{
		ID:        "ann_handley",
		Name:      "Ann Handley",
		Role:      "Content Marketing Pioneer",
		EmojiIcon: "📚",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Author of 'Everybody Writes'", Weight: 100},
			{ID: uuid.New().String(), Name: "Chief Content Officer MarketingProfs", Weight: 95},
			{ID: uuid.New().String(), Name: "Storytelling Advocate", Weight: 90},
			{ID: uuid.New().String(), Name: "Keynote Speaker", Weight: 88},
			{ID: uuid.New().String(), Name: "Newsletter 'Total ANNARCHY'", Weight: 85},
			{ID: uuid.New().String(), Name: "Co-Author 'Content Rules'", Weight: 82},
			{ID: uuid.New().String(), Name: "LinkedIn Influencer", Weight: 80},
			{ID: uuid.New().String(), Name: "Writing Coach", Weight: 78},
			{ID: uuid.New().String(), Name: "Digital Marketing Columnist", Weight: 75},
			{ID: uuid.New().String(), Name: "Global Keynote Lecturer", Weight: 72},
		},
	},
}

// Design persona list
var designPersonaList = []Person{
	{
		ID:        "don_norman",
		Name:      "Don Norman",
		Role:      "UX Pioneer",
		EmojiIcon: "🎨",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Author of 'The Design of Everyday Things'", Weight: 100},
			{ID: uuid.New().String(), Name: "Cognitive Scientist & Designer", Weight: 95},
			{ID: uuid.New().String(), Name: "Co-Founder Nielsen Norman Group", Weight: 90},
			{ID: uuid.New().String(), Name: "Human-Centered Design Advocate", Weight: 88},
			{ID: uuid.New().String(), Name: "Apple VP User Experience Alumni", Weight: 85},
			{ID: uuid.New().String(), Name: "Double Diamond Model Advocate", Weight: 82},
			{ID: uuid.New().String(), Name: "WDO President Emeritus", Weight: 80},
			{ID: uuid.New().String(), Name: "Design Education Mentor", Weight: 78},
			{ID: uuid.New().String(), Name: "Keynote Speaker", Weight: 75},
			{ID: uuid.New().String(), Name: "UX Researcher", Weight: 72},
		},
	},
	{
		ID:        "dieter_rams",
		Name:      "Dieter Rams",
		Role:      "Industrial Designer",
		EmojiIcon: "🖌️",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Chief Designer Braun (1955-1995)", Weight: 100},
			{ID: uuid.New().String(), Name: "10 Principles of Good Design Author", Weight: 95},
			{ID: uuid.New().String(), Name: "Functional Minimalism Icon", Weight: 90},
			{ID: uuid.New().String(), Name: "Influence on Apple Design", Weight: 88},
			{ID: uuid.New().String(), Name: "Furniture Designer at Vitsoe", Weight: 85},
			{ID: uuid.New().String(), Name: "Sustainable Design Advocate", Weight: 82},
			{ID: uuid.New().String(), Name: "German Industrial Designer", Weight: 80},
			{ID: uuid.New().String(), Name: "MoMA Exhibited Works", Weight: 78},
			{ID: uuid.New().String(), Name: "Royal Designer for Industry", Weight: 75},
			{ID: uuid.New().String(), Name: "Global Keynote Speaker", Weight: 72},
		},
	},
}

var universalPersonaList = []Person{
	{
		ID:        "daniel_kahneman",
		Name:      "Daniel Kahneman",
		Role:      "Psychologist & Nobel Laureate",
		EmojiIcon: "🧠",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Nobel Prize in Economic Sciences (2002)", Weight: 100},
			{ID: uuid.New().String(), Name: "Prospect Theory Creator", Weight: 95},
			{ID: uuid.New().String(), Name: "Author of 'Thinking, Fast and Slow'", Weight: 95},
			{ID: uuid.New().String(), Name: "Cognitive Bias Researcher", Weight: 90},
			{ID: uuid.New().String(), Name: "Behavioral Economics Pioneer", Weight: 90},
			{ID: uuid.New().String(), Name: "Judgment & Decision-Making Scholar", Weight: 85},
		},
	},
	{
		ID:        "elon_musk",
		Name:      "Elon Musk",
		Role:      "Entrepreneur & Innovator",
		EmojiIcon: "🚀",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "CEO of Tesla", Weight: 100},
			{ID: uuid.New().String(), Name: "Founder & CEO of SpaceX", Weight: 100},
			{ID: uuid.New().String(), Name: "Neuralink & The Boring Company Founder", Weight: 90},
			{ID: uuid.New().String(), Name: "Reusable Rocket Engineering Visionary", Weight: 90},
			{ID: uuid.New().String(), Name: "Mars Colonization Advocate", Weight: 85},
			{ID: uuid.New().String(), Name: "Sustainability & Clean Energy Promoter", Weight: 85},
		},
	},
	{
		ID:        "brene_brown",
		Name:      "Brené Brown",
		Role:      "Research Professor & Author",
		EmojiIcon: "🤝",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Author of 'Dare to Lead' & 'Daring Greatly'", Weight: 100},
			{ID: uuid.New().String(), Name: "TED Talk 'The Power of Vulnerability'", Weight: 95},
			{ID: uuid.New().String(), Name: "Vulnerability & Courage Researcher", Weight: 95},
			{ID: uuid.New().String(), Name: "Leadership & Empathy Coach", Weight: 90},
			{ID: uuid.New().String(), Name: "Shame Resilience Theory Developer", Weight: 88},
			{ID: uuid.New().String(), Name: "Atlas of the Heart Host", Weight: 80},
		},
	},
	{
		ID:        "tim_ferriss",
		Name:      "Tim Ferriss",
		Role:      "Author & Podcaster",
		EmojiIcon: "⏱️",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Author of 'The 4-Hour Workweek'", Weight: 100},
			{ID: uuid.New().String(), Name: "Lifestyle Design Advocate", Weight: 95},
			{ID: uuid.New().String(), Name: "Host of 'The Tim Ferriss Show' Podcast", Weight: 95},
			{ID: uuid.New().String(), Name: "Self-Experimentation & Optimization Expert", Weight: 90},
			{ID: uuid.New().String(), Name: "Early-Stage Tech Investor", Weight: 85},
			{ID: uuid.New().String(), Name: "Productivity & Time-Management Hacker", Weight: 85},
		},
	},
}

var moderationPersonaList = []Person{
	{
		ID:        "yoel_roth",
		Name:      "Yoel Roth",
		Role:      "Trust & Safety Specialist",
		EmojiIcon: "🛡️",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Former Head of Trust & Safety at Twitter", Weight: 100},
			{ID: uuid.New().String(), Name: "Content Moderation Policy Leader", Weight: 95},
			{ID: uuid.New().String(), Name: "Misinformation Mitigation Advocate", Weight: 90},
			{ID: uuid.New().String(), Name: "Online Harassment Researcher", Weight: 85},
			{ID: uuid.New().String(), Name: "Safety Standards Architect", Weight: 82},
		},
	},
	{
		ID:        "monika_bickert",
		Name:      "Monika Bickert",
		Role:      "VP Content Policy, Meta",
		EmojiIcon: "📜",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Leads Meta Content Policy Team", Weight: 100},
			{ID: uuid.New().String(), Name: "Former Federal Prosecutor", Weight: 90},
			{ID: uuid.New().String(), Name: "Global Policy Development Expert", Weight: 88},
			{ID: uuid.New().String(), Name: "Community Standards Evangelist", Weight: 85},
			{ID: uuid.New().String(), Name: "Stakeholder Engagement Specialist", Weight: 80},
		},
	},
	{
		ID:        "alex_stamos",
		Name:      "Alex Stamos",
		Role:      "Security & Safety Researcher",
		EmojiIcon: "🔐",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Former Facebook Chief Security Officer", Weight: 100},
			{ID: uuid.New().String(), Name: "Director at Stanford Internet Observatory", Weight: 95},
			{ID: uuid.New().String(), Name: "Disinformation Response Strategist", Weight: 92},
			{ID: uuid.New().String(), Name: "Child Safety Online Advocate", Weight: 88},
			{ID: uuid.New().String(), Name: "Cybersecurity Thought Leader", Weight: 85},
		},
	},
	{
		ID:        "claire_wardle",
		Name:      "Claire Wardle",
		Role:      "Misinformation Researcher",
		EmojiIcon: "📰",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Co-Founder of First Draft", Weight: 100},
			{ID: uuid.New().String(), Name: "Expert on User-Generated Content Verification", Weight: 95},
			{ID: uuid.New().String(), Name: "UN & WHO Information Integrity Advisor", Weight: 90},
			{ID: uuid.New().String(), Name: "Content Moderation Educator", Weight: 88},
			{ID: uuid.New().String(), Name: "Conference Keynote Speaker", Weight: 80},
		},
	},
	{
		ID:        "del_harvey",
		Name:      "Del Harvey",
		Role:      "Trust & Safety Executive",
		EmojiIcon: "🛡️",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Former VP Trust & Safety at Twitter", Weight: 100},
			{ID: uuid.New().String(), Name: "Online Safety & Abuse Prevention Expert", Weight: 95},
			{ID: uuid.New().String(), Name: "Crisis Response Policy Developer", Weight: 90},
			{ID: uuid.New().String(), Name: "Child Exploitation Prevention Advocate", Weight: 88},
			{ID: uuid.New().String(), Name: "Trust & Safety Advisory Board Member", Weight: 80},
		},
	},
}

var gameReviewersPersonaList = []Person{
	{
		ID:        "jeff_gerstmann",
		Name:      "Jeff Gerstmann",
		Role:      "Game Journalist & Podcaster",
		EmojiIcon: "🎮",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Co-Founder of Giant Bomb", Weight: 100},
			{ID: uuid.New().String(), Name: "Former GameSpot Editorial Director", Weight: 95},
			{ID: uuid.New().String(), Name: "Host of 'The Jeff Gerstmann Show' Podcast", Weight: 90},
			{ID: uuid.New().String(), Name: "30+ Years Reviewing Games", Weight: 88},
			{ID: uuid.New().String(), Name: "Livestream Quick Looks Pioneer", Weight: 85},
			{ID: uuid.New().String(), Name: "Video-Game History Encyclopedist", Weight: 82},
		},
	},
	{
		ID:        "angry_joe",
		Name:      "Joe Vargas (Angry Joe)",
		Role:      "Game Reviewer & YouTuber",
		EmojiIcon: "😡",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Host of AngryJoeShow", Weight: 100},
			{ID: uuid.New().String(), Name: "In-Depth Video Reviews", Weight: 95},
			{ID: uuid.New().String(), Name: "Consumer Advocacy Focus", Weight: 90},
			{ID: uuid.New().String(), Name: "Live Streams & First Impressions", Weight: 88},
			{ID: uuid.New().String(), Name: "Board-Game Reviewer", Weight: 80},
			{ID: uuid.New().String(), Name: "Movie & TV Cross-Media Critic", Weight: 78},
		},
	},
	{
		ID:        "yahtzee_croshaw",
		Name:      "Ben 'Yahtzee' Croshaw",
		Role:      "Game Critic & Developer",
		EmojiIcon: "📝",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Creator of Zero Punctuation", Weight: 100},
			{ID: uuid.New().String(), Name: "Fast-Paced Video Reviews", Weight: 95},
			{ID: uuid.New().String(), Name: "Comedy Writing Style", Weight: 90},
			{ID: uuid.New().String(), Name: "Indie Game Developer", Weight: 88},
			{ID: uuid.New().String(), Name: "Author of Gaming Novels", Weight: 85},
			{ID: uuid.New().String(), Name: "Podcast Host & Columnist", Weight: 75},
		},
	},
	{
		ID:        "keza_macdonald",
		Name:      "Keza MacDonald",
		Role:      "Video-Games Editor",
		EmojiIcon: "🎤",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Games Editor at The Guardian", Weight: 100},
			{ID: uuid.New().String(), Name: "Former IGN UK Editor-in-Chief", Weight: 95},
			{ID: uuid.New().String(), Name: "Co-Host of 'Spawn Point' Podcast", Weight: 90},
			{ID: uuid.New().String(), Name: "BAFTA Games Awards Juror", Weight: 88},
			{ID: uuid.New().String(), Name: "Advocate for Diversity in Gaming", Weight: 85},
			{ID: uuid.New().String(), Name: "Industry Analyst & Commentator", Weight: 82},
		},
	},
}

var promptEngineeringPersonaList = []Person{
	{
		ID:        "riley_goodside",
		Name:      "Riley Goodside",
		Role:      "Staff Prompt Engineer",
		EmojiIcon: "🔧",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Early GPT-3 prompt demonstrations", Weight: 100},
			{ID: uuid.New().String(), Name: "LLM jailbreak technique specialist", Weight: 98},
			{ID: uuid.New().String(), Name: "Prompt injection taxonomy author", Weight: 95},
			{ID: uuid.New().String(), Name: "Chain-of-thought scaffolding expert", Weight: 93},
			{ID: uuid.New().String(), Name: "Completion parameter tuning guide", Weight: 90},
			{ID: uuid.New().String(), Name: "Few-shot pattern library curator", Weight: 88},
			{ID: uuid.New().String(), Name: "LLM safety evaluation researcher", Weight: 85},
			{ID: uuid.New().String(), Name: "Open-source prompt datasets contributor", Weight: 82},
		},
	},
	{
		ID:        "ethan_mollick",
		Name:      "Ethan Mollick",
		Role:      "Wharton Professor",
		EmojiIcon: "📚",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Author of practical prompt guides", Weight: 100},
			{ID: uuid.New().String(), Name: "AI-first pedagogy framework designer", Weight: 97},
			{ID: uuid.New().String(), Name: "Live prompt workshops for educators", Weight: 94},
			{ID: uuid.New().String(), Name: "Assessment of prompt-driven creativity", Weight: 92},
			{ID: uuid.New().String(), Name: "System prompt design for classrooms", Weight: 90},
			{ID: uuid.New().String(), Name: "Case studies on student prompt use", Weight: 88},
			{ID: uuid.New().String(), Name: "Substack ‘One Useful Thing’ prompt series", Weight: 86},
			{ID: uuid.New().String(), Name: "Research on reflective prompting", Weight: 84},
		},
	},
	{
		ID:        "jason_wei",
		Name:      "Jason Wei",
		Role:      "Research Scientist (Google DeepMind)",
		EmojiIcon: "📝",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Chain-of-thought paper co-author", Weight: 100},
			{ID: uuid.New().String(), Name: "Reasoning prompt technique inventor", Weight: 97},
			{ID: uuid.New().String(), Name: "Scaling laws aware prompt design", Weight: 94},
			{ID: uuid.New().String(), Name: "Benchmark prompts for BIG-Bench tasks", Weight: 92},
			{ID: uuid.New().String(), Name: "Self-consistency prompting research", Weight: 90},
			{ID: uuid.New().String(), Name: "Model hallucination mitigation prompts", Weight: 88},
			{ID: uuid.New().String(), Name: "Sparse decoding prompt studies", Weight: 85},
			{ID: uuid.New().String(), Name: "Multilingual prompt evaluation", Weight: 83},
		},
	},
	{
		ID:        "dale_markowitz",
		Name:      "Dale Markowitz",
		Role:      "Generative AI Advocate (Google Cloud)",
		EmojiIcon: "☁️",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Vertex AI prompt best-practice author", Weight: 100},
			{ID: uuid.New().String(), Name: "YouTube series Prompt Engineering 101", Weight: 97},
			{ID: uuid.New().String(), Name: "Hands-on labs for LLM API usage", Weight: 94},
			{ID: uuid.New().String(), Name: "Safety & toxicity filtering prompts", Weight: 92},
			{ID: uuid.New().String(), Name: "Grounding data with RAG prompts", Weight: 90},
			{ID: uuid.New().String(), Name: "Vision-text multimodal prompting", Weight: 88},
			{ID: uuid.New().String(), Name: "Prompt performance cost analysis", Weight: 86},
			{ID: uuid.New().String(), Name: "Industry case-study prompt playbooks", Weight: 84},
		},
	},
	{
		ID:        "logan_kilpatrick",
		Name:      "Logan Kilpatrick",
		Role:      "Developer Relations (OpenAI)",
		EmojiIcon: "🤝",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Community prompt showcase curator", Weight: 100},
			{ID: uuid.New().String(), Name: "Function-calling prompt guidelines", Weight: 97},
			{ID: uuid.New().String(), Name: "Prompt troubleshooting office hours", Weight: 94},
			{ID: uuid.New().String(), Name: "API usage best-practices author", Weight: 92},
			{ID: uuid.New().String(), Name: "Embedding search prompt recipes", Weight: 90},
			{ID: uuid.New().String(), Name: "Role & system prompt pattern demos", Weight: 88},
			{ID: uuid.New().String(), Name: "Migration guides for prompt upgrades", Weight: 86},
			{ID: uuid.New().String(), Name: "Prompt hackathon mentorship", Weight: 84},
		},
	},
	{
		ID:        "andrew_mayne",
		Name:      "Andrew Mayne",
		Role:      "Author & Former OpenAI Creative Director",
		EmojiIcon: "🎩",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Author Prompt Engineering for Dummies", Weight: 100},
			{ID: uuid.New().String(), Name: "DALL·E narrative prompt expert", Weight: 97},
			{ID: uuid.New().String(), Name: "Interactive fiction prompt systems", Weight: 94},
			{ID: uuid.New().String(), Name: "AI-assisted storytelling workshops", Weight: 92},
			{ID: uuid.New().String(), Name: "Prompt-based character generation", Weight: 90},
			{ID: uuid.New().String(), Name: "Visual prompt iteration techniques", Weight: 88},
			{ID: uuid.New().String(), Name: "Podcast host on creative prompting", Weight: 86},
			{ID: uuid.New().String(), Name: "Author of AI crime thriller novels", Weight: 84},
		},
	},
	{
		ID:        "jay_alammar",
		Name:      "Jay Alammar",
		Role:      "AI Explainer",
		EmojiIcon: "📊",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Visual guide to prompt patterns", Weight: 100},
			{ID: uuid.New().String(), Name: "Transformers-illustrated series", Weight: 97},
			{ID: uuid.New().String(), Name: "Embedding prompt demos", Weight: 94},
			{ID: uuid.New().String(), Name: "OpenAI cookbook contributions", Weight: 92},
			{ID: uuid.New().String(), Name: "Prompt diagrams for ReAct & CoT", Weight: 90},
			{ID: uuid.New().String(), Name: "BERTology prompting tutorials", Weight: 88},
			{ID: uuid.New().String(), Name: "Cross-modal prompt visualizations", Weight: 86},
			{ID: uuid.New().String(), Name: "Conference talks on prompt design", Weight: 84},
		},
	},
	{
		ID:        "shreya_shankar",
		Name:      "Shreya Shankar",
		Role:      "Researcher & Educator",
		EmojiIcon: "🎓",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Stanford CS25 prompt engineering lecturer", Weight: 100},
			{ID: uuid.New().String(), Name: "Helm & RAG eval frameworks author", Weight: 97},
			{ID: uuid.New().String(), Name: "Data-centric prompt iteration methods", Weight: 94},
			{ID: uuid.New().String(), Name: "Guardrail & policy prompt patterns", Weight: 92},
			{ID: uuid.New().String(), Name: "LLM observability tooling creator", Weight: 90},
			{ID: uuid.New().String(), Name: "Prompt library open-source maintainer", Weight: 88},
			{ID: uuid.New().String(), Name: "Active learning prompt workflows", Weight: 86},
			{ID: uuid.New().String(), Name: "Talks on evaluation driven prompting", Weight: 84},
		},
	},
	{
		ID:        "gwern_branwen",
		Name:      "Gwern Branwen",
		Role:      "Independent Researcher",
		EmojiIcon: "🔍",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Long-form GPT essay experiments", Weight: 100},
			{ID: uuid.New().String(), Name: "Prompt scaling & sampling studies", Weight: 97},
			{ID: uuid.New().String(), Name: "Style transfer prompting research", Weight: 94},
			{ID: uuid.New().String(), Name: "Temperature & top-p parameter guides", Weight: 92},
			{ID: uuid.New().String(), Name: "Synthetic text detection evaluations", Weight: 90},
			{ID: uuid.New().String(), Name: "Merging prompts with latent diffusion", Weight: 88},
			{ID: uuid.New().String(), Name: "Explorations of truncation tricks", Weight: 86},
			{ID: uuid.New().String(), Name: "Maintains extensive prompt corpora", Weight: 84},
		},
	},
	{
		ID:        "athena_promptopolis",
		Name:      "Dr. Athena Promptopolis",
		Role:      "Senior Prompt Engineer",
		EmojiIcon: "🧠",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Has read: OpenAI Prompt Guide, DeepMind Prompt Patterns, Anthropic Constitutional AI", Weight: 100},
			{ID: uuid.New().String(), Name: "Masters chain-of-thought, tree-of-thought, ReAct", Weight: 97},
			{ID: uuid.New().String(), Name: "Fluent in few-shot, zero-shot, self-consistency", Weight: 94},
			{ID: uuid.New().String(), Name: "Designs retrieval-augmented prompts with vector DBs", Weight: 92},
			{ID: uuid.New().String(), Name: "Implements self-critique & reflection loops", Weight: 90},
			{ID: uuid.New().String(), Name: "Invented 'Socratic Sandwich' prompt pattern", Weight: 88},
			{ID: uuid.New().String(), Name: "Can compress prompts with token-efficient macros", Weight: 86},
			{ID: uuid.New().String(), Name: "Evaluates prompts using automatic metric pipelines", Weight: 84},
		},
	},
}

var copyWritingPersonaList = []Person{
	{
		ID:        "david_ogilvy",
		Name:      "David Ogilvy",
		Role:      "Father of Advertising",
		EmojiIcon: "🎯",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Author of 'Ogilvy on Advertising'", Weight: 100},
			{ID: uuid.New().String(), Name: "Headline Crafting Master", Weight: 98},
			{ID: uuid.New().String(), Name: "Direct Response Copy Techniques", Weight: 95},
			{ID: uuid.New().String(), Name: "Brand Storytelling Pioneer", Weight: 92},
			{ID: uuid.New().String(), Name: "Research-Driven Messaging", Weight: 90},
			{ID: uuid.New().String(), Name: "Split-Test Advocate", Weight: 85},
		},
	},
	{
		ID:        "joanna_wiebe",
		Name:      "Joanna Wiebe",
		Role:      "Founder of Copyhackers",
		EmojiIcon: "📝",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Conversion Copywriting Expert", Weight: 100},
			{ID: uuid.New().String(), Name: "Creator of 'Copy School'", Weight: 97},
			{ID: uuid.New().String(), Name: "Voice-of-Customer Research Champion", Weight: 95},
			{ID: uuid.New().String(), Name: "SaaS Onboarding Email Sequences", Weight: 92},
			{ID: uuid.New().String(), Name: "A/B Testing Methodology", Weight: 90},
			{ID: uuid.New().String(), Name: "Persuasion Framework Teacher", Weight: 88},
		},
	},
	{
		ID:        "gary_halbert",
		Name:      "Gary Halbert",
		Role:      "Legendary Direct-Response Copywriter",
		EmojiIcon: "💌",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Author of 'The Boron Letters'", Weight: 100},
			{ID: uuid.New().String(), Name: "Long-Form Sales Letter Wizard", Weight: 98},
			{ID: uuid.New().String(), Name: "AIDA & PAS Framework Mastery", Weight: 95},
			{ID: uuid.New().String(), Name: "List-Building Strategist", Weight: 92},
			{ID: uuid.New().String(), Name: "Handwritten Copy Technique", Weight: 90},
			{ID: uuid.New().String(), Name: "Offer Positioning Specialist", Weight: 88},
		},
	},
	{
		ID:        "eugene_schwartz",
		Name:      "Eugene Schwartz",
		Role:      "Breakthrough Advertising Author",
		EmojiIcon: "📈",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Stages of Market Awareness Model", Weight: 100},
			{ID: uuid.New().String(), Name: "Power Headline Formulas", Weight: 97},
			{ID: uuid.New().String(), Name: "Desire Amplification Techniques", Weight: 95},
			{ID: uuid.New().String(), Name: "Sophistication Level Targeting", Weight: 92},
			{ID: uuid.New().String(), Name: "Magazine Ad Copy Legend", Weight: 90},
			{ID: uuid.New().String(), Name: "High-ROI Mail-Order Campaigns", Weight: 88},
		},
	},
	{
		ID:        "joe_sugarman",
		Name:      "Joe Sugarman",
		Role:      "BluBlocker & JS&A Copy Pro",
		EmojiIcon: "🕶️",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Author 'The Adweek Copywriting Handbook'", Weight: 100},
			{ID: uuid.New().String(), Name: "Psychological Triggers Expert", Weight: 97},
			{ID: uuid.New().String(), Name: "Story-Driven Product Descriptions", Weight: 95},
			{ID: uuid.New().String(), Name: "Television Direct-Response Pioneer", Weight: 92},
			{ID: uuid.New().String(), Name: "Copy Flow 'Greased Slide' Technique", Weight: 90},
			{ID: uuid.New().String(), Name: "Urgency & Scarcity Messaging", Weight: 88},
		},
	},
}

// Vim / Neovim / LazyVim
var vimPersonaList = []Person{
	{
		ID:        "bram_moolenaar",
		Name:      "Bram Moolenaar",
		Role:      "Creator of Vim",
		EmojiIcon: "💻",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Original author of Vim (1991)", Weight: 100},
			{ID: uuid.New().String(), Name: "Vimscript language architect", Weight: 95},
			{ID: uuid.New().String(), Name: "Charityware licensing pioneer", Weight: 90},
			{ID: uuid.New().String(), Name: "Ex mode & modal editing guru", Weight: 88},
			{ID: uuid.New().String(), Name: "Optimization & portability expert", Weight: 85},
		},
	},
	{
		ID:        "tj_devries",
		Name:      "TJ DeVries",
		Role:      "Neovim Core Maintainer",
		EmojiIcon: "💻",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Telescope.nvim creator", Weight: 100},
			{ID: uuid.New().String(), Name: "Neovim Lua standard-bearer", Weight: 95},
			{ID: uuid.New().String(), Name: "LSP client implementation lead", Weight: 92},
			{ID: uuid.New().String(), Name: "Live-coding educator & speaker", Weight: 90},
			{ID: uuid.New().String(), Name: "Plugin ecosystem evangelist", Weight: 88},
		},
	},
	{
		ID:        "christian_folke",
		Name:      "Christian (folke)",
		Role:      "LazyVim & Plugin Author",
		EmojiIcon: "💻",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "lazy.nvim package manager author", Weight: 100},
			{ID: uuid.New().String(), Name: "LazyVim starter template creator", Weight: 97},
			{ID: uuid.New().String(), Name: "UI/UX plugin suite (lualine, which-key)", Weight: 94},
			{ID: uuid.New().String(), Name: "Lua-first workflow promoter", Weight: 92},
			{ID: uuid.New().String(), Name: "Color-scheme & aesthetics specialist", Weight: 88},
		},
	},
	{
		ID:        "drew_neil",
		Name:      "Drew Neil",
		Role:      "Practical Vim Author",
		EmojiIcon: "💻",
		Features: []Feature{
			{ID: uuid.New().String(), Name: "Author of 'Practical Vim'", Weight: 100},
			{ID: uuid.New().String(), Name: "Vimcasts tutorial founder", Weight: 97},
			{ID: uuid.New().String(), Name: "Text-object & motion teaching", Weight: 94},
			{ID: uuid.New().String(), Name: "Conference speaker & trainer", Weight: 92},
			{ID: uuid.New().String(), Name: "Refactoring with macros expert", Weight: 88},
		},
	},
}

var GroupedTeamMembersPresets = map[string][]Person{
	"💻 Developers":         developersPersonaList,
	"⭐ Universal":          universalPersonaList,
	"📣 Marketing":          marketingPersonaList,
	"💼 Sales":              salesPersonaList,
	"🎧 Customer Support":   customerSupportPersonaList,
	"💰 Finance":            financePersonaList,
	"🧠 Product Management": productManagementPersonaList,
	"📊 Data Science":       dataSciencePersonaList,
	"🎥 Content Creation":   contentCreationPersonaList,
	"🎨 Design":             designPersonaList,
	"🛡️ Moderation":        moderationPersonaList,
	"🎮 Game Reviewers":     gameReviewersPersonaList,
	"🤖 Prompt Engineering": promptEngineeringPersonaList,
	"✍️ Copywriting":       copyWritingPersonaList,
	"🖥️  Vim/Neovim":       vimPersonaList,
}
